{
  "type": "record",
  "name": "ClickstreamEvent",
  "namespace": "com.streampulse",
  "fields": [
    {"name": "event_id",        "type": "string"},
    {"name": "user_id",         "type": "string"},
    {"name": "session_id",      "type": "string"},
    {"name": "event_type",      "type": {
      "type": "enum",
      "name": "EventType",
      "symbols": ["page_view", "product_click", "add_to_cart", "remove_from_cart", "search"]
    }},
    {"name": "product_id",      "type": ["null", "string"], "default": null},
    {"name": "page_url",        "type": "string"},
    {"name": "referrer",        "type": ["null", "string"], "default": null},
    {"name": "device_type",     "type": {
      "type": "enum",
      "name": "DeviceType",
      "symbols": ["desktop", "mobile", "tablet"]
    }},
    {"name": "event_timestamp", "type": "long",
     "logicalType": "timestamp-millis"}
  ]
}