{
  "type": "record",
  "name": "OrderEvent",
  "namespace": "com.streampulse",
  "fields": [
    {"name": "order_id",        "type": "string"},
    {"name": "user_id",         "type": "string"},
    {"name": "session_id",      "type": "string"},
    {"name": "items",           "type": {
      "type": "array",
      "items": {
        "type": "record",
        "name": "OrderItem",
        "fields": [
          {"name": "product_id",   "type": "string"},
          {"name": "product_name", "type": "string"},
          {"name": "category",     "type": "string"},
          {"name": "quantity",     "type": "int"},
          {"name": "unit_price",   "type": "double"},
          {"name": "subtotal",     "type": "double"}
        ]
      }
    }},
    {"name": "total_amount",    "type": "double"},
    {"name": "currency",        "type": "string", "default": "USD"},
    {"name": "payment_method",  "type": {
      "type": "enum",
      "name": "PaymentMethod",
      "symbols": ["credit_card", "debit_card", "paypal", "crypto"]
    }},
    {"name": "order_timestamp", "type": "long",
     "logicalType": "timestamp-millis"}
  ]
}